name: 'Apply SUSFS Patches'
description: 'Copy base SUSFS patches and apply version-specific fake patches'
inputs:
  version:
    description: 'Kernel config version (e.g., android15-6.6)'
    required: true
  sublevel:
    description: 'Kernel sublevel'
    required: true
  os_patch_level:
    description: 'OS patch level (e.g., 2024-07)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Apply Kernel SUSFS Patches
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        # Apply base SUSFS patches
        cp "${{ github.workspace }}/susfs4ksu/kernel_patches/fs/"* "${{ github.workspace }}/kernel/fs/"
        cp "${{ github.workspace }}/susfs4ksu/kernel_patches/include/linux/"* "${{ github.workspace }}/kernel/include/linux/"
        cp ${{ github.workspace }}/susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.version }}.patch ./

    - name: Apply Android 14 6.1 Fake Patches
      shell: bash
      if: inputs.version == 'android14-6.1'
      working-directory: ${{ github.workspace }}/kernel
      run: |
        if [ "${{ inputs.sublevel }}" -ge "157" ]; then
          echo "Applying namespace.c Android 14 6.1 Fake Patch"
          sed -i '/^#include <trace\/hooks\/blk.h>$/d' fs/namespace.c
        fi

    - name: Apply Kernel SUSFS Patches
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        patch -p1 < 50_add_susfs_in_gki-${{ inputs.version }}.patch
