name: 'Clean Kernel Flags'
description: 'Clean dirty flags'

runs:
  using: "composite"
  steps:
    - name: Clean Dirty Flags and ABI Exports
      shell: bash
      working-directory: ${{ github.workspace }}/kernel
      run: |
        # Clean dirty flags and ABI exports based on build system
        sed -i 's/-dirty//' scripts/setlocalversion

        # Commit changes to avoid dirty state during build
        cd ${{ github.workspace }}/kernel
        git add .
        git commit -m "Wild: Clean Dirty Flag"
